platform: linux/arm

clone:
  git:
    image: quay.io/armswarm/drone-git

pipeline:
  build_and_publish:
    image: quay.io/armswarm/drone-docker
    secrets: [ docker_registry, docker_username, docker_password ]
    repo: quay.io/armswarm/node_exporter
    build_args:
      - NODE_EXPORTER_VERSION=0.15.2
    tag: [ "0.15.2", "0.15", "latest" ]
    when:
      branch: master
      event: push

  notify:
    image: quay.io/armswarm/drone-slack
    secrets: [ slack_webhook, plugin_channel, plugin_template ]
    when:
      status: [ failure, success ]
